export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';

export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';

export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';

export const FETCH_VENDORS_START = 'FETCH_VENDORS_START';

export const FETCH_VENDORS_SUCCESS = 'FETCH_VENDORS_SUCCESS';

export const FETCH_VENDORS_ERROR = 'FETCH_VENDORS_ERROR';

export const FETCH_PROMOTION_START = 'FETCH_PROMOTION_START';

export const FETCH_PROMOTION_SUCCESS = 'FETCH_PROMOTION_SUCCESS';

export const FETCH_PROMOTION_ERROR = 'FETCH_PROMOTION_ERROR';

export const SEARCH_QUERY = 'SEARCH_QUERY';

export const FILTER_VENDOR = 'FILTER_VENDOR';
